auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
exclude: [shower,themes]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: Marcelo Stein de Lima Sousa
    url:  http://pagi.wikidot.com/
    company:
        name: DACEX | UTFPR
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
